In [1]:
import pandas as pd

In [5]:
# import data sources
raw_data = pd.read_csv("data/email_phishing_data.csv")
raw_data

,num_words,num_unique_words,num_stopwords,num_links,num_unique_domains,num_email_addresses,num_spelling_errors,num_urgent_keywords,label
0,140,94,52,0,0,0,0,0,0
1,5,5,1,0,0,0,0,0,0
2,34,32,15,0,0,0,0,0,0
3,6,6,2,0,0,0,0,0,0
4,9,9,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
524841,782,327,301,2,2,2,52,1,0
524842,36,30,11,0,0,0,4,0,1
524843,61,46,11,0,0,0,3,0,0
524844,213,136,89,0,0,0,18,0,0
524845,26,24,3,0,0,0,2,0,0

In [4]:
((raw_data['label'].value_counts()) / len(raw_data)) * 100

label
0    98.675993
1     1.324007
Name: count, dtype: float64